### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by beckham894** [wwwjfy/legend-mac#5]
cd src -> make後出現error

`./jymain.h:8:10: fatal error: 'SDL.h' file not found`

**Comment by wwwjfy** [comment]
SDL 没有装或者路径没有设置好吧

**Comment by beckham894** [comment]
已經安裝了SDL但怎樣設置路徑?

**Comment by wwwjfy** [comment]
可以看下 Makefile。pkg-config 是不是能找到 sdl，以及输出的那些目录是否存在。
