### ISSUE TITLE
'smpeg/smpeg.h' file not found

### ISSUE THREAD

**Issue by williamyeh** [wwwjfy/legend-mac#7]
boss,

上一個duplicate issue SDL.h not found 是因為在我的mac 沒安裝 pkg-config 
brew install pkg-config 後解決了

但是現在下make, 出現以下
./jymain.h:13:14: fatal error: 'smpeg/smpeg.h' file not found
我把include改成以前的 #include <smpeg.h> 也是無法，但是brew 已經有裝smpeg.h了

可否指點一下，感恩

**Comment by wwwjfy** [comment]
可以看下 <homebrew dir>/include 里有没有 smpeg，gcc 加上 -I/usr/local/include / -I/opt/homebrew/include

**Comment by williamyeh** [comment]
gcc 加上 -I /usr/local/include / -I /opt/homebrew/include 就成功編譯 並能執行
