### ISSUE TITLE
鍵盤長按不支援？

### ISSUE THREAD

**Issue by williamyeh** [wwwjfy/legend-mac#8]
剛成功的complie 與執行了，很感動
想請問處理使用者keyboard input的代碼在哪裡？
人物在走路時，我似乎需要一直按一步才走一步，無法長按

如果能夠處理這個就更好了

**Comment by wwwjfy** [comment]
可以尝试调整 bin/config.lua 里 KeyRepeat 一部分的配置

**Comment by williamyeh** [comment]
changed bin/config.lua 
CONFIG.KeyRepeat from - to 1, works now, thanks
